[project]
name = "neuron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai[tools]>=0.130.0",
    "fastapi>=0.115.9",
    "redis>=6.2.0",
    "uvicorn[standard]>=0.34.3",
]

[tool.ruff]
line-length = 120
